name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Runs every time you push code

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Secret into HTML
        run: |
          sed -i "s/SECRET_PLACEHOLDER/$SH_ID/g" index.html
        env:
          SH_ID: ${{ secrets.GOOGLE_SHEET_ID }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
